"""ch-opendata-swiss provider.

opendata.swiss CKAN API. Search Swiss open datasets and
browse organizations and tags.

Homepage: https://opendata.swiss/

Auto-generated by tools/generate_provider.py.
"""

import logging
from collections.abc import Sequence
from typing import Any

from mcp import types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)

log = logging.getLogger(__name__)

PROVIDER_ID = "ch-opendata-swiss"
BASE_URL = "https://opendata.swiss/api/3/action"

RESOURCES: list[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: list[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# ch-opendata-package-search
###################


class ChOpendataPackageSearchParams(BaseModel):
    """Parameters for ch-opendata-package-search."""

    q: str | None = Field(
        None,
        description="Free-text query",
    )

    rows: int | None = Field(
        20,
        description="Number of results to return",
    )

    start: int | None = Field(
        0,
        description="Result offset",
    )


def fetch_ch_opendata_package_search(params: ChOpendataPackageSearchParams) -> Any:
    """Fetch data for the ch-opendata-package-search tool."""
    url = f"{BASE_URL}/package_search"
    query: dict = {}
    if params.q is not None:
        query["q"] = params.q
    if params.rows is not None:
        query["rows"] = params.rows
    if params.start is not None:
        query["start"] = params.start
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_ch_opendata_package_search(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the ch-opendata-package-search tool call."""
    try:
        params = ChOpendataPackageSearchParams(**(arguments or {}))
        data = fetch_ch_opendata_package_search(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling ch-opendata-package-search: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="ch-opendata-package-search",
        description="Search Swiss open datasets",
        input_schema=ChOpendataPackageSearchParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["ch-opendata-package-search"] = handle_ch_opendata_package_search


###################
# ch-opendata-organization-list
###################


class ChOpendataOrganizationListParams(BaseModel):
    """Parameters for ch-opendata-organization-list."""


def fetch_ch_opendata_organization_list(
    params: ChOpendataOrganizationListParams,
) -> Any:
    """Fetch data for the ch-opendata-organization-list tool."""
    url = f"{BASE_URL}/organization_list"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_ch_opendata_organization_list(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the ch-opendata-organization-list tool call."""
    try:
        params = ChOpendataOrganizationListParams(**(arguments or {}))
        data = fetch_ch_opendata_organization_list(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling ch-opendata-organization-list: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="ch-opendata-organization-list",
        description="List opendata.swiss organizations",
        input_schema=ChOpendataOrganizationListParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["ch-opendata-organization-list"] = handle_ch_opendata_organization_list


###################
# ch-opendata-tag-list
###################


class ChOpendataTagListParams(BaseModel):
    """Parameters for ch-opendata-tag-list."""


def fetch_ch_opendata_tag_list(params: ChOpendataTagListParams) -> Any:
    """Fetch data for the ch-opendata-tag-list tool."""
    url = f"{BASE_URL}/tag_list"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_ch_opendata_tag_list(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the ch-opendata-tag-list tool call."""
    try:
        params = ChOpendataTagListParams(**(arguments or {}))
        data = fetch_ch_opendata_tag_list(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling ch-opendata-tag-list: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="ch-opendata-tag-list",
        description="List opendata.swiss tags",
        input_schema=ChOpendataTagListParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["ch-opendata-tag-list"] = handle_ch_opendata_tag_list


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "ch-opendata-swiss",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
