"""de-govdata provider.

GovData Germany CKAN API. Search German public datasets,
and browse organizations and groups.

Homepage: https://www.govdata.de/

Auto-generated by tools/generate_provider.py.
"""

import logging
from collections.abc import Sequence
from typing import Any

from mcp import types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)

log = logging.getLogger(__name__)

PROVIDER_ID = "de-govdata"
BASE_URL = "https://www.govdata.de/ckan/api/3/action"

RESOURCES: list[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: list[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# de-govdata-package-search
###################


class DeGovdataPackageSearchParams(BaseModel):
    """Parameters for de-govdata-package-search."""

    q: str | None = Field(
        None,
        description="Free-text query",
    )

    rows: int | None = Field(
        20,
        description="Number of results to return",
    )

    start: int | None = Field(
        0,
        description="Result offset",
    )


def fetch_de_govdata_package_search(params: DeGovdataPackageSearchParams) -> Any:
    """Fetch data for the de-govdata-package-search tool."""
    url = f"{BASE_URL}/package_search"
    query: dict = {}
    if params.q is not None:
        query["q"] = params.q
    if params.rows is not None:
        query["rows"] = params.rows
    if params.start is not None:
        query["start"] = params.start
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_de_govdata_package_search(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the de-govdata-package-search tool call."""
    try:
        params = DeGovdataPackageSearchParams(**(arguments or {}))
        data = fetch_de_govdata_package_search(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling de-govdata-package-search: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="de-govdata-package-search",
        description="Search GovData datasets",
        input_schema=DeGovdataPackageSearchParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["de-govdata-package-search"] = handle_de_govdata_package_search


###################
# de-govdata-organization-list
###################


class DeGovdataOrganizationListParams(BaseModel):
    """Parameters for de-govdata-organization-list."""


def fetch_de_govdata_organization_list(params: DeGovdataOrganizationListParams) -> Any:
    """Fetch data for the de-govdata-organization-list tool."""
    url = f"{BASE_URL}/organization_list"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_de_govdata_organization_list(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the de-govdata-organization-list tool call."""
    try:
        params = DeGovdataOrganizationListParams(**(arguments or {}))
        data = fetch_de_govdata_organization_list(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling de-govdata-organization-list: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="de-govdata-organization-list",
        description="List GovData organizations",
        input_schema=DeGovdataOrganizationListParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["de-govdata-organization-list"] = handle_de_govdata_organization_list


###################
# de-govdata-group-list
###################


class DeGovdataGroupListParams(BaseModel):
    """Parameters for de-govdata-group-list."""


def fetch_de_govdata_group_list(params: DeGovdataGroupListParams) -> Any:
    """Fetch data for the de-govdata-group-list tool."""
    url = f"{BASE_URL}/group_list"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_de_govdata_group_list(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the de-govdata-group-list tool call."""
    try:
        params = DeGovdataGroupListParams(**(arguments or {}))
        data = fetch_de_govdata_group_list(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling de-govdata-group-list: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="de-govdata-group-list",
        description="List GovData groups",
        input_schema=DeGovdataGroupListParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["de-govdata-group-list"] = handle_de_govdata_group_list


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "de-govdata",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
