"""eu-euvd provider.

ENISA EU Vulnerability Database (EUVD) API for latest, exploited, critical, and filtered vulnerability search.

Homepage: https://euvd.enisa.europa.eu/apidoc

Auto-generated by tools/generate_provider.py.
"""


import logging
from typing import Any, List, Optional, Sequence

import mcp.types as types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)


log = logging.getLogger(__name__)

PROVIDER_ID = "eu-euvd"
BASE_URL = "https://euvdservices.enisa.europa.eu/api"

RESOURCES: List[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: List[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# euvd-latest-vulnerabilities
###################


class EuvdLatestVulnerabilitiesParams(BaseModel):
    """Parameters for euvd-latest-vulnerabilities."""

    pass


def fetch_euvd_latest_vulnerabilities(params: EuvdLatestVulnerabilitiesParams) -> Any:
    """Fetch data for the euvd-latest-vulnerabilities tool."""
    url = f"{BASE_URL}/lastvulnerabilities"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_euvd_latest_vulnerabilities(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the euvd-latest-vulnerabilities tool call."""
    try:
        params = EuvdLatestVulnerabilitiesParams(**(arguments or {}))
        data = fetch_euvd_latest_vulnerabilities(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling euvd-latest-vulnerabilities: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="euvd-latest-vulnerabilities",
        description="Fetch the latest vulnerability records from EUVD.",
        inputSchema=EuvdLatestVulnerabilitiesParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["euvd-latest-vulnerabilities"] = handle_euvd_latest_vulnerabilities


###################
# euvd-exploited-vulnerabilities
###################


class EuvdExploitedVulnerabilitiesParams(BaseModel):
    """Parameters for euvd-exploited-vulnerabilities."""

    pass


def fetch_euvd_exploited_vulnerabilities(params: EuvdExploitedVulnerabilitiesParams) -> Any:
    """Fetch data for the euvd-exploited-vulnerabilities tool."""
    url = f"{BASE_URL}/exploitedvulnerabilities"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_euvd_exploited_vulnerabilities(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the euvd-exploited-vulnerabilities tool call."""
    try:
        params = EuvdExploitedVulnerabilitiesParams(**(arguments or {}))
        data = fetch_euvd_exploited_vulnerabilities(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling euvd-exploited-vulnerabilities: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="euvd-exploited-vulnerabilities",
        description="Fetch the latest vulnerabilities marked as exploited by EUVD.",
        inputSchema=EuvdExploitedVulnerabilitiesParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["euvd-exploited-vulnerabilities"] = handle_euvd_exploited_vulnerabilities


###################
# euvd-critical-vulnerabilities
###################


class EuvdCriticalVulnerabilitiesParams(BaseModel):
    """Parameters for euvd-critical-vulnerabilities."""

    pass


def fetch_euvd_critical_vulnerabilities(params: EuvdCriticalVulnerabilitiesParams) -> Any:
    """Fetch data for the euvd-critical-vulnerabilities tool."""
    url = f"{BASE_URL}/criticalvulnerabilities"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_euvd_critical_vulnerabilities(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the euvd-critical-vulnerabilities tool call."""
    try:
        params = EuvdCriticalVulnerabilitiesParams(**(arguments or {}))
        data = fetch_euvd_critical_vulnerabilities(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling euvd-critical-vulnerabilities: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="euvd-critical-vulnerabilities",
        description="Fetch the latest critical vulnerabilities from EUVD.",
        inputSchema=EuvdCriticalVulnerabilitiesParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["euvd-critical-vulnerabilities"] = handle_euvd_critical_vulnerabilities


###################
# euvd-search-vulnerabilities
###################


class EuvdSearchVulnerabilitiesParams(BaseModel):
    """Parameters for euvd-search-vulnerabilities."""

    text: Optional[str] = Field(
        None,
        description="Free-text search term.",
    )

    vendor: Optional[str] = Field(
        None,
        min_length=1,
        description="Vendor filter such as Microsoft.",
    )

    product: Optional[str] = Field(
        None,
        min_length=1,
        description="Product filter such as Windows.",
    )

    assigner: Optional[str] = Field(
        None,
        min_length=1,
        description="Assigner filter.",
    )

    exploited: Optional[bool] = Field(
        None,
        description="Filter to exploited or non-exploited vulnerabilities.",
    )

    from_score: Optional[float] = Field(
        None,
        ge=0.0,
        le=10.0,
        description="Minimum score filter.",
    )

    to_score: Optional[float] = Field(
        None,
        ge=0.0,
        le=10.0,
        description="Maximum score filter.",
    )

    from_date: Optional[str] = Field(
        None,
        pattern=r"^\d{4}-\d{2}-\d{2}$",
        description="Lower published-date bound in YYYY-MM-DD format.",
    )

    to_date: Optional[str] = Field(
        None,
        pattern=r"^\d{4}-\d{2}-\d{2}$",
        description="Upper published-date bound in YYYY-MM-DD format.",
    )

    from_updated_date: Optional[str] = Field(
        None,
        pattern=r"^\d{4}-\d{2}-\d{2}$",
        description="Lower updated-date bound in YYYY-MM-DD format.",
    )

    to_updated_date: Optional[str] = Field(
        None,
        pattern=r"^\d{4}-\d{2}-\d{2}$",
        description="Upper updated-date bound in YYYY-MM-DD format.",
    )

    page: int = Field(
        default=0,
        ge=0,
        description="Zero-indexed page number.",
    )

    size: int = Field(
        default=20,
        ge=1,
        le=100,
        description="Number of results to return per page.",
    )


def fetch_euvd_search_vulnerabilities(params: EuvdSearchVulnerabilitiesParams) -> Any:
    """Fetch data for the euvd-search-vulnerabilities tool."""
    url = f"{BASE_URL}/search"
    query: dict = {}
    if params.text is not None:
        query["text"] = params.text
    if params.vendor is not None:
        query["vendor"] = params.vendor
    if params.product is not None:
        query["product"] = params.product
    if params.assigner is not None:
        query["assigner"] = params.assigner
    if params.exploited is not None:
        query["exploited"] = params.exploited
    if params.from_score is not None:
        query["fromScore"] = params.from_score
    if params.to_score is not None:
        query["toScore"] = params.to_score
    if params.from_date is not None:
        query["fromDate"] = params.from_date
    if params.to_date is not None:
        query["toDate"] = params.to_date
    if params.from_updated_date is not None:
        query["fromUpdatedDate"] = params.from_updated_date
    if params.to_updated_date is not None:
        query["toUpdatedDate"] = params.to_updated_date
    query["page"] = params.page
    query["size"] = params.size
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_euvd_search_vulnerabilities(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the euvd-search-vulnerabilities tool call."""
    try:
        params = EuvdSearchVulnerabilitiesParams(**(arguments or {}))
        data = fetch_euvd_search_vulnerabilities(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling euvd-search-vulnerabilities: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="euvd-search-vulnerabilities",
        description="Search EUVD vulnerabilities by score, exploited flag, vendor, product, text, assigner, and date filters.",
        inputSchema=EuvdSearchVulnerabilitiesParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["euvd-search-vulnerabilities"] = handle_euvd_search_vulnerabilities


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "eu-euvd",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
