"""global-solarsystem provider.

Le Systeme Solaire public API for solar-system objects,
body metadata, and catalog counts.

Homepage: https://api.le-systeme-solaire.net/

Auto-generated by tools/generate_provider.py.
"""

import logging
from collections.abc import Sequence
from typing import Any

from mcp import types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)

log = logging.getLogger(__name__)

PROVIDER_ID = "global-solarsystem"
BASE_URL = "https://api.le-systeme-solaire.net/rest"

RESOURCES: list[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: list[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# solarsystem-list-bodies
###################


class SolarsystemListBodiesParams(BaseModel):
    """Parameters for solarsystem-list-bodies."""

    filter: str | None = Field(
        None,
        description="Optional API filter expression",
    )

    data: str | None = Field(
        None,
        description="Comma-separated fields to include",
    )


def fetch_solarsystem_list_bodies(params: SolarsystemListBodiesParams) -> Any:
    """Fetch data for the solarsystem-list-bodies tool."""
    url = f"{BASE_URL}/bodies"
    query: dict = {}
    if params.filter is not None:
        query["filter"] = params.filter
    if params.data is not None:
        query["data"] = params.data
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_solarsystem_list_bodies(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the solarsystem-list-bodies tool call."""
    try:
        params = SolarsystemListBodiesParams(**(arguments or {}))
        data = fetch_solarsystem_list_bodies(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling solarsystem-list-bodies: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="solarsystem-list-bodies",
        description="List solar-system bodies with optional query filter",
        input_schema=SolarsystemListBodiesParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["solarsystem-list-bodies"] = handle_solarsystem_list_bodies


###################
# solarsystem-get-body
###################


class SolarsystemGetBodyParams(BaseModel):
    """Parameters for solarsystem-get-body."""

    body_id: str = Field(
        ...,
        description="Body identifier (e.g. terre, mars, lune)",
    )


def fetch_solarsystem_get_body(params: SolarsystemGetBodyParams) -> Any:
    """Fetch data for the solarsystem-get-body tool."""
    from urllib.parse import quote

    url = f"{BASE_URL}/bodies/{quote(params.body_id, safe='')}"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_solarsystem_get_body(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the solarsystem-get-body tool call."""
    try:
        params = SolarsystemGetBodyParams(**(arguments or {}))
        data = fetch_solarsystem_get_body(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling solarsystem-get-body: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="solarsystem-get-body",
        description="Get details for a solar-system body by body ID",
        input_schema=SolarsystemGetBodyParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["solarsystem-get-body"] = handle_solarsystem_get_body


###################
# solarsystem-known-count
###################


class SolarsystemKnownCountParams(BaseModel):
    """Parameters for solarsystem-known-count."""


def fetch_solarsystem_known_count(params: SolarsystemKnownCountParams) -> Any:
    """Fetch data for the solarsystem-known-count tool."""
    url = f"{BASE_URL}/knowncount"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_solarsystem_known_count(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the solarsystem-known-count tool call."""
    try:
        params = SolarsystemKnownCountParams(**(arguments or {}))
        data = fetch_solarsystem_known_count(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling solarsystem-known-count: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="solarsystem-known-count",
        description="Get known object counts by category",
        input_schema=SolarsystemKnownCountParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["solarsystem-known-count"] = handle_solarsystem_known_count


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "global-solarsystem",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
