"""global-ssllabs provider.

Qualys SSL Labs API for public TLS configuration analysis and endpoint details.

Homepage: https://api.ssllabs.com/api/v3

Auto-generated by tools/generate_provider.py.
"""

import logging
from collections.abc import Sequence
from typing import Any

from mcp import types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)

log = logging.getLogger(__name__)

PROVIDER_ID = "global-ssllabs"
BASE_URL = "https://api.ssllabs.com/api/v3"

RESOURCES: list[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: list[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# ssllabs-analyze
###################


class SsllabsAnalyzeParams(BaseModel):
    """Parameters for ssllabs-analyze."""

    host: str = Field(
        ...,
        min_length=1,
        description="Hostname to analyze, such as example.com.",
    )

    publish: str | None = Field(
        None,
        pattern=r"^(on|off)$",
        description="Set to on or off to publish results on SSL Labs.",
    )

    start_new: str | None = Field(
        None,
        pattern=r"^(on|off)$",
        description="Set to on to force a new assessment.",
    )

    from_cache: str | None = Field(
        None,
        pattern=r"^(on|off)$",
        description="Set to on or off to control cache usage.",
    )

    all: str | None = Field(
        None,
        pattern=r"^(on|off)$",
        description="Set to on to include all status messages.",
    )

    ignore_mismatch: str | None = Field(
        None,
        pattern=r"^(on|off)$",
        description="Set to on to continue despite hostname mismatch.",
    )


def fetch_ssllabs_analyze(params: SsllabsAnalyzeParams) -> Any:
    """Fetch data for the ssllabs-analyze tool."""
    url = f"{BASE_URL}/analyze"
    query: dict = {}
    query["host"] = params.host
    if params.publish is not None:
        query["publish"] = params.publish
    if params.start_new is not None:
        query["startNew"] = params.start_new
    if params.from_cache is not None:
        query["fromCache"] = params.from_cache
    if params.all is not None:
        query["all"] = params.all
    if params.ignore_mismatch is not None:
        query["ignoreMismatch"] = params.ignore_mismatch
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_ssllabs_analyze(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the ssllabs-analyze tool call."""
    try:
        params = SsllabsAnalyzeParams(**(arguments or {}))
        data = fetch_ssllabs_analyze(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling ssllabs-analyze: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="ssllabs-analyze",
        description="Start or retrieve a TLS analysis for a public host.",
        input_schema=SsllabsAnalyzeParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["ssllabs-analyze"] = handle_ssllabs_analyze


###################
# ssllabs-endpoint-data
###################


class SsllabsEndpointDataParams(BaseModel):
    """Parameters for ssllabs-endpoint-data."""

    host: str = Field(
        ...,
        min_length=1,
        description="Hostname used for the analysis.",
    )

    ip: str = Field(
        ...,
        min_length=1,
        description="Endpoint IP address from the analyze response.",
    )

    from_cache: str | None = Field(
        None,
        pattern=r"^(on|off)$",
        description="Set to on or off to control cache usage.",
    )


def fetch_ssllabs_endpoint_data(params: SsllabsEndpointDataParams) -> Any:
    """Fetch data for the ssllabs-endpoint-data tool."""
    url = f"{BASE_URL}/getEndpointData"
    query: dict = {}
    query["host"] = params.host
    query["ip"] = params.ip
    if params.from_cache is not None:
        query["fromCache"] = params.from_cache
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_ssllabs_endpoint_data(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the ssllabs-endpoint-data tool call."""
    try:
        params = SsllabsEndpointDataParams(**(arguments or {}))
        data = fetch_ssllabs_endpoint_data(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling ssllabs-endpoint-data: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="ssllabs-endpoint-data",
        description="Fetch detailed TLS analysis results for a specific analyzed endpoint IP.",
        input_schema=SsllabsEndpointDataParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["ssllabs-endpoint-data"] = handle_ssllabs_endpoint_data


###################
# ssllabs-info
###################


class SsllabsInfoParams(BaseModel):
    """Parameters for ssllabs-info."""


def fetch_ssllabs_info(params: SsllabsInfoParams) -> Any:
    """Fetch data for the ssllabs-info tool."""
    url = f"{BASE_URL}/info"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_ssllabs_info(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the ssllabs-info tool call."""
    try:
        params = SsllabsInfoParams(**(arguments or {}))
        data = fetch_ssllabs_info(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling ssllabs-info: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="ssllabs-info",
        description="Fetch SSL Labs API engine metadata and assessment capacity information.",
        input_schema=SsllabsInfoParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["ssllabs-info"] = handle_ssllabs_info


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "global-ssllabs",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
