"""global-pwned-passwords provider.

Have I Been Pwned Pwned Passwords range API for anonymous SHA-1 prefix lookups.

Homepage: https://haveibeenpwned.com/API/v3#SearchingPwnedPasswordsByRange

Auto-generated by tools/generate_provider.py.
"""

import logging
from collections.abc import Sequence
from typing import Any

from mcp import types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    MAX_RESPONSE_CHARS,
    create_mcp_server,
    http_get,
    run_server,
)

log = logging.getLogger(__name__)

PROVIDER_ID = "global-pwned-passwords"
BASE_URL = "https://api.pwnedpasswords.com"

RESOURCES: list[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: list[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# pwned-passwords-range
###################


class PwnedPasswordsRangeParams(BaseModel):
    """Parameters for pwned-passwords-range."""

    sha1_prefix: str = Field(
        ...,
        min_length=5,
        max_length=5,
        pattern=r"^[A-Fa-f0-9]{5}$",
        description="First 5 hexadecimal characters of a SHA-1 password hash.",
    )


def fetch_pwned_passwords_range(params: PwnedPasswordsRangeParams) -> str:
    """Fetch data for the pwned-passwords-range tool."""
    url = f"{BASE_URL}/range/{params.sha1_prefix.upper()}"
    query: dict = {}
    response = http_get(
        url,
        params=query or None,
        provider=PROVIDER_ID,
        headers={"Accept": "text/plain"},
    )
    return response.text


async def handle_pwned_passwords_range(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the pwned-passwords-range tool call."""
    try:
        params = PwnedPasswordsRangeParams(**(arguments or {}))
        data = fetch_pwned_passwords_range(params)
        return [types.TextContent(type="text", text=(data or "")[:MAX_RESPONSE_CHARS])]
    except Exception as e:
        log.error(f"Error handling pwned-passwords-range: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="pwned-passwords-range",
        description="Look up breached-password hash suffixes for a 5-character SHA-1 prefix using k-anonymity.",
        input_schema=PwnedPasswordsRangeParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["pwned-passwords-range"] = handle_pwned_passwords_range


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "global-pwned-passwords",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
