"""global-mcp-registry provider.

Official MCP Server Registry — discover, search, and inspect servers published
to the Model Context Protocol registry. No API key required.

Homepage: https://registry.modelcontextprotocol.io

Auto-generated by tools/generate_provider.py.
"""

import logging
from typing import Any, List, Optional, Sequence

import mcp.types as types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)


log = logging.getLogger(__name__)

PROVIDER_ID = "global-mcp-registry"
BASE_URL = "https://registry.modelcontextprotocol.io"

RESOURCES: List[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: List[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# mcp.registry.search
###################


class McpRegistrySearchParams(BaseModel):
    """Parameters for mcp.registry.search."""

    q: Optional[str] = Field(
        None,
        description="Keyword search query (e.g. 'weather', 'database', 'github')",
    )

    limit: Optional[int] = Field(
        20,
        description="Max results to return",
    )

    cursor: Optional[str] = Field(
        None,
        description="Pagination cursor from previous response metadata.nextCursor",
    )


def fetch_mcp_registry_search(params: McpRegistrySearchParams) -> Any:
    """Fetch data for the mcp.registry.search tool."""
    url = f"{BASE_URL}/v0/servers"
    query: dict = {}
    if params.q is not None:
        query["q"] = params.q
    if params.limit is not None:
        query["limit"] = params.limit
    if params.cursor is not None:
        query["cursor"] = params.cursor
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_mcp_registry_search(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the mcp.registry.search tool call."""
    try:
        params = McpRegistrySearchParams(**(arguments or {}))
        data = fetch_mcp_registry_search(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling mcp.registry.search: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="mcp.registry.search",
        description="Search the MCP server registry by keyword",
        inputSchema=McpRegistrySearchParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["mcp.registry.search"] = handle_mcp_registry_search


###################
# mcp.registry.list
###################


class McpRegistryListParams(BaseModel):
    """Parameters for mcp.registry.list."""

    limit: Optional[int] = Field(
        50,
        description="Max results to return",
    )

    cursor: Optional[str] = Field(
        None,
        description="Pagination cursor from previous response metadata.nextCursor",
    )


def fetch_mcp_registry_list(params: McpRegistryListParams) -> Any:
    """Fetch data for the mcp.registry.list tool."""
    url = f"{BASE_URL}/v0/servers"
    query: dict = {}
    if params.limit is not None:
        query["limit"] = params.limit
    if params.cursor is not None:
        query["cursor"] = params.cursor
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_mcp_registry_list(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the mcp.registry.list tool call."""
    try:
        params = McpRegistryListParams(**(arguments or {}))
        data = fetch_mcp_registry_list(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling mcp.registry.list: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="mcp.registry.list",
        description="List all servers in the MCP registry, newest first",
        inputSchema=McpRegistryListParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["mcp.registry.list"] = handle_mcp_registry_list


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "global-mcp-registry",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
