"""global-doaj provider.

Directory of Open Access Journals (DOAJ) search API for open-access journals and articles.

Homepage: https://doaj.org/

Auto-generated by tools/generate_provider.py.
"""


import logging
from typing import Any, List, Sequence

import mcp.types as types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)


log = logging.getLogger(__name__)

PROVIDER_ID = "global-doaj"
BASE_URL = "https://doaj.org/api/v2/search"

RESOURCES: List[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: List[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# doaj-search-articles
###################


class DoajSearchArticlesParams(BaseModel):
    """Parameters for doaj-search-articles."""

    q: str = Field(
        ...,
        min_length=1,
        description="Search query, such as cancer, climate, or author:Smith.",
    )

    page: int = Field(
        default=1,
        ge=1,
        description="1-indexed page number.",
    )

    page_size: int = Field(
        default=20,
        ge=1,
        le=100,
        description="Number of results to return per page.",
    )


def fetch_doaj_search_articles(params: DoajSearchArticlesParams) -> Any:
    """Fetch data for the doaj-search-articles tool."""
    url = f"{BASE_URL}/articles/"
    query: dict = {}
    query["q"] = params.q
    query["page"] = params.page
    query["pageSize"] = params.page_size
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_doaj_search_articles(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the doaj-search-articles tool call."""
    try:
        params = DoajSearchArticlesParams(**(arguments or {}))
        data = fetch_doaj_search_articles(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling doaj-search-articles: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="doaj-search-articles",
        description="Search open-access articles indexed by DOAJ.",
        inputSchema=DoajSearchArticlesParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["doaj-search-articles"] = handle_doaj_search_articles


###################
# doaj-search-journals
###################


class DoajSearchJournalsParams(BaseModel):
    """Parameters for doaj-search-journals."""

    q: str = Field(
        ...,
        min_length=1,
        description="Search query, such as biology, publisher:Springer, or issn:1234-5678.",
    )

    page: int = Field(
        default=1,
        ge=1,
        description="1-indexed page number.",
    )

    page_size: int = Field(
        default=20,
        ge=1,
        le=100,
        description="Number of results to return per page.",
    )


def fetch_doaj_search_journals(params: DoajSearchJournalsParams) -> Any:
    """Fetch data for the doaj-search-journals tool."""
    url = f"{BASE_URL}/journals/"
    query: dict = {}
    query["q"] = params.q
    query["page"] = params.page
    query["pageSize"] = params.page_size
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_doaj_search_journals(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the doaj-search-journals tool call."""
    try:
        params = DoajSearchJournalsParams(**(arguments or {}))
        data = fetch_doaj_search_journals(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling doaj-search-journals: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="doaj-search-journals",
        description="Search open-access journals indexed by DOAJ.",
        inputSchema=DoajSearchJournalsParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["doaj-search-journals"] = handle_doaj_search_journals


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "global-doaj",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
