"""global-crtsh provider.

Certificate Transparency search via crt.sh for domains and certificate names.

Homepage: https://crt.sh

Auto-generated by tools/generate_provider.py.
"""

import logging
from collections.abc import Sequence
from typing import Any

from mcp import types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)

log = logging.getLogger(__name__)

PROVIDER_ID = "global-crtsh"
BASE_URL = "https://crt.sh"

RESOURCES: list[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: list[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# crtsh-search-certificates
###################


class CrtshSearchCertificatesParams(BaseModel):
    """Parameters for crtsh-search-certificates."""

    q: str = Field(
        ...,
        min_length=1,
        description="Domain or query string such as example.com or %.example.com.",
    )

    exclude: str | None = Field(
        None,
        min_length=1,
        description="Optional exclusion flags such as expired or expired,ca.",
    )


def fetch_crtsh_search_certificates(params: CrtshSearchCertificatesParams) -> Any:
    """Fetch data for the crtsh-search-certificates tool."""
    url = f"{BASE_URL}/"
    query: dict = {}
    query["q"] = params.q
    query["output"] = "json"
    if params.exclude is not None:
        query["exclude"] = params.exclude
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_crtsh_search_certificates(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the crtsh-search-certificates tool call."""
    try:
        params = CrtshSearchCertificatesParams(**(arguments or {}))
        data = fetch_crtsh_search_certificates(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling crtsh-search-certificates: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="crtsh-search-certificates",
        description="Search certificate transparency records for a domain or query string.",
        input_schema=CrtshSearchCertificatesParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["crtsh-search-certificates"] = handle_crtsh_search_certificates


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "global-crtsh",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
