"""global-chembl provider.

ChEMBL chemical biology database API from EMBL-EBI. Search molecules,
inspect molecule records, and query bioactivity data.

Homepage: https://www.ebi.ac.uk/chembl/

Auto-generated by tools/generate_provider.py.
"""

import logging
from typing import Any, List, Optional, Sequence

import mcp.types as types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)


log = logging.getLogger(__name__)

PROVIDER_ID = "global-chembl"
BASE_URL = "https://www.ebi.ac.uk/chembl/api/data"

RESOURCES: List[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: List[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# chembl-search-molecules
###################


class ChemblSearchMoleculesParams(BaseModel):
    """Parameters for chembl-search-molecules."""

    molecule_synonym: Optional[str] = Field(
        None,
        description="Optional molecule synonym/text filter",
    )

    limit: Optional[int] = Field(
        20,
        description="Maximum number of records to return",
    )

    offset: Optional[int] = Field(
        0,
        description="Pagination offset",
    )


def fetch_chembl_search_molecules(params: ChemblSearchMoleculesParams) -> Any:
    """Fetch data for the chembl-search-molecules tool."""
    url = f"{BASE_URL}/molecule.json"
    query: dict = {}
    if params.molecule_synonym is not None:
        query["molecule_synonym"] = params.molecule_synonym
    if params.limit is not None:
        query["limit"] = params.limit
    if params.offset is not None:
        query["offset"] = params.offset
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_chembl_search_molecules(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the chembl-search-molecules tool call."""
    try:
        params = ChemblSearchMoleculesParams(**(arguments or {}))
        data = fetch_chembl_search_molecules(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling chembl-search-molecules: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="chembl-search-molecules",
        description="Search ChEMBL molecules with optional text filter",
        inputSchema=ChemblSearchMoleculesParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["chembl-search-molecules"] = handle_chembl_search_molecules


###################
# chembl-get-molecule
###################


class ChemblGetMoleculeParams(BaseModel):
    """Parameters for chembl-get-molecule."""

    chembl_id: str = Field(
        ...,
        description="ChEMBL molecule identifier (e.g. CHEMBL25)",
    )


def fetch_chembl_get_molecule(params: ChemblGetMoleculeParams) -> Any:
    """Fetch data for the chembl-get-molecule tool."""
    from urllib.parse import quote

    url = f"{BASE_URL}/molecule/{quote(params.chembl_id, safe='')}.json"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_chembl_get_molecule(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the chembl-get-molecule tool call."""
    try:
        params = ChemblGetMoleculeParams(**(arguments or {}))
        data = fetch_chembl_get_molecule(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling chembl-get-molecule: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="chembl-get-molecule",
        description="Get detailed ChEMBL molecule information by ChEMBL ID",
        inputSchema=ChemblGetMoleculeParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["chembl-get-molecule"] = handle_chembl_get_molecule


###################
# chembl-list-activities
###################


class ChemblListActivitiesParams(BaseModel):
    """Parameters for chembl-list-activities."""

    molecule_chembl_id: Optional[str] = Field(
        None,
        description="Optional molecule ChEMBL ID filter",
    )

    limit: Optional[int] = Field(
        20,
        description="Maximum number of activities to return",
    )

    offset: Optional[int] = Field(
        0,
        description="Pagination offset",
    )


def fetch_chembl_list_activities(params: ChemblListActivitiesParams) -> Any:
    """Fetch data for the chembl-list-activities tool."""
    url = f"{BASE_URL}/activity.json"
    query: dict = {}
    if params.molecule_chembl_id is not None:
        query["molecule_chembl_id"] = params.molecule_chembl_id
    if params.limit is not None:
        query["limit"] = params.limit
    if params.offset is not None:
        query["offset"] = params.offset
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_chembl_list_activities(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the chembl-list-activities tool call."""
    try:
        params = ChemblListActivitiesParams(**(arguments or {}))
        data = fetch_chembl_list_activities(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling chembl-list-activities: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="chembl-list-activities",
        description="List ChEMBL activities with optional molecule filter",
        inputSchema=ChemblListActivitiesParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["chembl-list-activities"] = handle_chembl_list_activities


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "global-chembl",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
