"""global-circl-cve provider.

CIRCL public CVE search API for recent CVEs, vendor/product browsing, and CVE detail lookups.

Homepage: https://www.circl.lu/services/cve-search/

Auto-generated by tools/generate_provider.py.
"""

import logging
from typing import Any, List, Sequence

import mcp.types as types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)


log = logging.getLogger(__name__)

PROVIDER_ID = "global-circl-cve"
BASE_URL = "https://cve.circl.lu/api"

RESOURCES: List[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: List[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# circl-cve-last
###################


class CirclCveLastParams(BaseModel):
    """Parameters for circl-cve-last."""

    limit: int = Field(
        ...,
        ge=1,
        le=100,
        description="Number of recent CVEs to return.",
    )


def fetch_circl_cve_last(params: CirclCveLastParams) -> Any:
    """Fetch data for the circl-cve-last tool."""
    url = f"{BASE_URL}/last/{params.limit}"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_circl_cve_last(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the circl-cve-last tool call."""
    try:
        params = CirclCveLastParams(**(arguments or {}))
        data = fetch_circl_cve_last(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling circl-cve-last: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="circl-cve-last",
        description="Fetch the most recent CVEs from CIRCL.",
        inputSchema=CirclCveLastParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["circl-cve-last"] = handle_circl_cve_last


###################
# circl-cve-get
###################


class CirclCveGetParams(BaseModel):
    """Parameters for circl-cve-get."""

    cve_id: str = Field(
        ...,
        min_length=1,
        description="CVE identifier such as CVE-2024-3094.",
    )


def fetch_circl_cve_get(params: CirclCveGetParams) -> Any:
    """Fetch data for the circl-cve-get tool."""
    url = f"{BASE_URL}/cve/{params.cve_id}"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_circl_cve_get(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the circl-cve-get tool call."""
    try:
        params = CirclCveGetParams(**(arguments or {}))
        data = fetch_circl_cve_get(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling circl-cve-get: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="circl-cve-get",
        description="Fetch detailed information for a specific CVE id.",
        inputSchema=CirclCveGetParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["circl-cve-get"] = handle_circl_cve_get


###################
# circl-cve-browse-vendors
###################


class CirclCveBrowseVendorsParams(BaseModel):
    """Parameters for circl-cve-browse-vendors."""

    pass


def fetch_circl_cve_browse_vendors(params: CirclCveBrowseVendorsParams) -> Any:
    """Fetch data for the circl-cve-browse-vendors tool."""
    url = f"{BASE_URL}/browse"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_circl_cve_browse_vendors(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the circl-cve-browse-vendors tool call."""
    try:
        params = CirclCveBrowseVendorsParams(**(arguments or {}))
        data = fetch_circl_cve_browse_vendors(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling circl-cve-browse-vendors: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="circl-cve-browse-vendors",
        description="List vendors present in CIRCL's CVE database.",
        inputSchema=CirclCveBrowseVendorsParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["circl-cve-browse-vendors"] = handle_circl_cve_browse_vendors


###################
# circl-cve-browse-products
###################


class CirclCveBrowseProductsParams(BaseModel):
    """Parameters for circl-cve-browse-products."""

    vendor: str = Field(
        ...,
        min_length=1,
        description="Vendor name such as microsoft or oracle.",
    )


def fetch_circl_cve_browse_products(params: CirclCveBrowseProductsParams) -> Any:
    """Fetch data for the circl-cve-browse-products tool."""
    url = f"{BASE_URL}/browse/{params.vendor}"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_circl_cve_browse_products(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the circl-cve-browse-products tool call."""
    try:
        params = CirclCveBrowseProductsParams(**(arguments or {}))
        data = fetch_circl_cve_browse_products(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling circl-cve-browse-products: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="circl-cve-browse-products",
        description="List products associated with a given vendor in CIRCL's CVE database.",
        inputSchema=CirclCveBrowseProductsParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["circl-cve-browse-products"] = handle_circl_cve_browse_products


###################
# circl-cve-search
###################


class CirclCveSearchParams(BaseModel):
    """Parameters for circl-cve-search."""

    vendor: str = Field(
        ...,
        min_length=1,
        description="Vendor name such as oracle.",
    )

    product: str = Field(
        ...,
        min_length=1,
        description="Product name such as mysql.",
    )


def fetch_circl_cve_search(params: CirclCveSearchParams) -> Any:
    """Fetch data for the circl-cve-search tool."""
    url = f"{BASE_URL}/search"
    query: dict = {}
    query["vendor"] = params.vendor
    query["product"] = params.product
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_circl_cve_search(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the circl-cve-search tool call."""
    try:
        params = CirclCveSearchParams(**(arguments or {}))
        data = fetch_circl_cve_search(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling circl-cve-search: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="circl-cve-search",
        description="Search CVEs for a vendor and product combination.",
        inputSchema=CirclCveSearchParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["circl-cve-search"] = handle_circl_cve_search


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "global-circl-cve",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
