"""global-hackernews provider.

Hacker News public Firebase API. Fetch top/new story IDs,
item details, and user profiles without authentication.

Homepage: https://github.com/HackerNews/API

Auto-generated by tools/generate_provider.py.
"""

import logging
from typing import Any, List, Sequence

import mcp.types as types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)


log = logging.getLogger(__name__)

PROVIDER_ID = "global-hackernews"
BASE_URL = "https://hacker-news.firebaseio.com/v0"

RESOURCES: List[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: List[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# hackernews-top-stories
###################


class HackernewsTopStoriesParams(BaseModel):
    """Parameters for hackernews-top-stories."""

    pass


def fetch_hackernews_top_stories(params: HackernewsTopStoriesParams) -> Any:
    """Fetch data for the hackernews-top-stories tool."""
    url = f"{BASE_URL}/topstories.json"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_hackernews_top_stories(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the hackernews-top-stories tool call."""
    try:
        params = HackernewsTopStoriesParams(**(arguments or {}))
        data = fetch_hackernews_top_stories(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling hackernews-top-stories: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="hackernews-top-stories",
        description="List top story IDs from Hacker News",
        inputSchema=HackernewsTopStoriesParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["hackernews-top-stories"] = handle_hackernews_top_stories


###################
# hackernews-new-stories
###################


class HackernewsNewStoriesParams(BaseModel):
    """Parameters for hackernews-new-stories."""

    pass


def fetch_hackernews_new_stories(params: HackernewsNewStoriesParams) -> Any:
    """Fetch data for the hackernews-new-stories tool."""
    url = f"{BASE_URL}/newstories.json"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_hackernews_new_stories(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the hackernews-new-stories tool call."""
    try:
        params = HackernewsNewStoriesParams(**(arguments or {}))
        data = fetch_hackernews_new_stories(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling hackernews-new-stories: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="hackernews-new-stories",
        description="List newest story IDs from Hacker News",
        inputSchema=HackernewsNewStoriesParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["hackernews-new-stories"] = handle_hackernews_new_stories


###################
# hackernews-get-item
###################


class HackernewsGetItemParams(BaseModel):
    """Parameters for hackernews-get-item."""

    item_id: int = Field(
        ...,
        description="Hacker News item ID",
    )


def fetch_hackernews_get_item(params: HackernewsGetItemParams) -> Any:
    """Fetch data for the hackernews-get-item tool."""
    url = f"{BASE_URL}/item/{params.item_id}.json"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_hackernews_get_item(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the hackernews-get-item tool call."""
    try:
        params = HackernewsGetItemParams(**(arguments or {}))
        data = fetch_hackernews_get_item(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling hackernews-get-item: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="hackernews-get-item",
        description="Get a Hacker News item by ID (story/comment/job/poll)",
        inputSchema=HackernewsGetItemParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["hackernews-get-item"] = handle_hackernews_get_item


###################
# hackernews-get-user
###################


class HackernewsGetUserParams(BaseModel):
    """Parameters for hackernews-get-user."""

    username: str = Field(
        ...,
        description="Hacker News username",
    )


def fetch_hackernews_get_user(params: HackernewsGetUserParams) -> Any:
    """Fetch data for the hackernews-get-user tool."""
    url = f"{BASE_URL}/user/{params.username}.json"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_hackernews_get_user(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the hackernews-get-user tool call."""
    try:
        params = HackernewsGetUserParams(**(arguments or {}))
        data = fetch_hackernews_get_user(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling hackernews-get-user: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="hackernews-get-user",
        description="Get a Hacker News user profile by username",
        inputSchema=HackernewsGetUserParams.model_json_schema(),
    )
)
TOOLS_HANDLERS["hackernews-get-user"] = handle_hackernews_get_user


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "global-hackernews",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
