"""global-rest-countries provider.

Country reference data — borders, capitals, currencies, languages, populations, timezones, and regions for 250+ countries.

Homepage: https://restcountries.com/

Auto-generated by tools/generate_provider.py.
"""

import logging
from collections.abc import Sequence
from typing import Any
from urllib.parse import quote

from mcp import types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)

log = logging.getLogger(__name__)

PROVIDER_ID = "global-rest-countries"
BASE_URL = "https://restcountries.com/v3.1"

RESOURCES: list[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: list[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# restcountries-search-by-name
###################


class RestcountriesSearchByNameParams(BaseModel):
    """Parameters for restcountries-search-by-name."""

    name: str = Field(
        ...,
        min_length=1,
        description="Country name or partial name, such as Germany or united.",
    )


def fetch_restcountries_search_by_name(params: RestcountriesSearchByNameParams) -> Any:
    """Fetch data for the restcountries-search-by-name tool."""
    url = f"{BASE_URL}/name/{quote(params.name, safe='')}"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_restcountries_search_by_name(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the restcountries-search-by-name tool call."""
    try:
        params = RestcountriesSearchByNameParams(**(arguments or {}))
        data = fetch_restcountries_search_by_name(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling restcountries-search-by-name: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="restcountries-search-by-name",
        description="Search countries by full or partial common/official name.",
        input_schema=RestcountriesSearchByNameParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["restcountries-search-by-name"] = handle_restcountries_search_by_name


###################
# restcountries-get-by-code
###################


class RestcountriesGetByCodeParams(BaseModel):
    """Parameters for restcountries-get-by-code."""

    code: str = Field(
        ...,
        min_length=1,
        description="Country code such as DE, DEU, 276, or US.",
    )


def fetch_restcountries_get_by_code(params: RestcountriesGetByCodeParams) -> Any:
    """Fetch data for the restcountries-get-by-code tool."""
    url = f"{BASE_URL}/alpha/{quote(params.code, safe='')}"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_restcountries_get_by_code(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the restcountries-get-by-code tool call."""
    try:
        params = RestcountriesGetByCodeParams(**(arguments or {}))
        data = fetch_restcountries_get_by_code(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling restcountries-get-by-code: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="restcountries-get-by-code",
        description="Fetch one country by ISO 3166 alpha-2, alpha-3, or numeric code.",
        input_schema=RestcountriesGetByCodeParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["restcountries-get-by-code"] = handle_restcountries_get_by_code


###################
# restcountries-list-by-region
###################


class RestcountriesListByRegionParams(BaseModel):
    """Parameters for restcountries-list-by-region."""

    region: str = Field(
        ...,
        min_length=1,
        description="Geographic region such as Europe, Asia, Africa, Oceania, or Americas.",
    )


def fetch_restcountries_list_by_region(params: RestcountriesListByRegionParams) -> Any:
    """Fetch data for the restcountries-list-by-region tool."""
    url = f"{BASE_URL}/region/{quote(params.region, safe='')}"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_restcountries_list_by_region(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the restcountries-list-by-region tool call."""
    try:
        params = RestcountriesListByRegionParams(**(arguments or {}))
        data = fetch_restcountries_list_by_region(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling restcountries-list-by-region: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="restcountries-list-by-region",
        description="List countries in a geographic region such as Europe, Asia, or Americas.",
        input_schema=RestcountriesListByRegionParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["restcountries-list-by-region"] = handle_restcountries_list_by_region


###################
# restcountries-list-all
###################


class RestcountriesListAllParams(BaseModel):
    """Parameters for restcountries-list-all."""


def fetch_restcountries_list_all(params: RestcountriesListAllParams) -> Any:
    """Fetch data for the restcountries-list-all tool."""
    url = f"{BASE_URL}/all"
    query: dict = {}
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_restcountries_list_all(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the restcountries-list-all tool call."""
    try:
        params = RestcountriesListAllParams(**(arguments or {}))
        data = fetch_restcountries_list_all(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling restcountries-list-all: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="restcountries-list-all",
        description="List all countries with their reference metadata.",
        input_schema=RestcountriesListAllParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["restcountries-list-all"] = handle_restcountries_list_all


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "global-rest-countries",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
