"""us-nc-onemap provider.

NC OneMap ArcGIS REST services provider.

Homepage: https://www.nconemap.gov/

Auto-generated by tools/generate_provider.py.
"""

import logging
from collections.abc import Sequence
from typing import Any

from mcp import types
from pydantic import BaseModel, Field

from meta_data_mcp.utils import (
    create_mcp_server,
    http_get,
    run_server,
    serialize_for_llm,
)

log = logging.getLogger(__name__)

PROVIDER_ID = "us-nc-onemap"
BASE_URL = "https://services.nconemap.gov/secure/rest/services"

RESOURCES: list[Any] = []
RESOURCES_HANDLERS: dict[str, Any] = {}
TOOLS: list[types.Tool] = []
TOOLS_HANDLERS: dict[str, Any] = {}


###################
# us-nc-onemap-list-services
###################


class UsNcOnemapListServicesParams(BaseModel):
    """Parameters for us-nc-onemap-list-services."""

    f: str | None = Field(
        "json",
        description="ArcGIS response format.",
    )


def fetch_us_nc_onemap_list_services(params: UsNcOnemapListServicesParams) -> Any:
    """Fetch data for the us-nc-onemap-list-services tool."""
    url = f"{BASE_URL}/"
    query: dict = {}
    if params.f is not None:
        query["f"] = params.f
    response = http_get(url, params=query or None, provider=PROVIDER_ID)
    return response.json()


async def handle_us_nc_onemap_list_services(
    arguments: dict[str, Any] | None = None,
) -> Sequence[types.TextContent]:
    """Handle the us-nc-onemap-list-services tool call."""
    try:
        params = UsNcOnemapListServicesParams(**(arguments or {}))
        data = fetch_us_nc_onemap_list_services(params)
        return [types.TextContent(type="text", text=serialize_for_llm(data))]
    except Exception as e:
        log.error(f"Error handling us-nc-onemap-list-services: {e}")
        raise


TOOLS.append(
    types.Tool(
        name="us-nc-onemap-list-services",
        description="List NC OneMap ArcGIS REST services.",
        input_schema=UsNcOnemapListServicesParams.model_json_schema(),
    ),
)
TOOLS_HANDLERS["us-nc-onemap-list-services"] = handle_us_nc_onemap_list_services


async def main(transport: str = "stdio", port: int = 8000, host: str = "127.0.0.1"):
    server = create_mcp_server(
        "us-nc-onemap",
        RESOURCES,
        RESOURCES_HANDLERS,
        TOOLS,
        TOOLS_HANDLERS,
    )
    await run_server(server, transport, port, host)


if __name__ == "__main__":
    import anyio

    anyio.run(main)
