"""Auto-generated tests for the global-circl-cve provider.

Generated by tools/generate_provider.py — feel free to extend with
tool-specific assertions once the provider stabilizes.
"""

from unittest.mock import Mock, patch

import httpx
import pytest

from meta_data_mcp.providers.global_circl_cve import (
    CirclCveBrowseProductsParams,
    CirclCveGetParams,
    CirclCveLastParams,
    CirclCveSearchParams,
    fetch_circl_cve_browse_products,
    fetch_circl_cve_get,
    fetch_circl_cve_last,
    fetch_circl_cve_search,
    handle_circl_cve_last,
    handle_circl_cve_get,
    handle_circl_cve_browse_vendors,
    handle_circl_cve_browse_products,
    handle_circl_cve_search,
)


@pytest.fixture
def anyio_backend():
    return "asyncio"


def _ok(payload):
    response = Mock()
    response.json.return_value = payload
    response.raise_for_status = Mock()
    response.status_code = 200
    response.headers = {}
    return response


def test_fetch_circl_cve_last_uses_limit_in_path():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok([{"id": "CVE-2026-0001"}])
        result = fetch_circl_cve_last(CirclCveLastParams(limit=5))
        assert result[0]["id"] == "CVE-2026-0001"
        assert mock_get.call_args[0][0].endswith("/last/5")


def test_fetch_circl_cve_get_uses_cve_id_in_path():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"id": "CVE-2024-3094"})
        result = fetch_circl_cve_get(CirclCveGetParams(cve_id="CVE-2024-3094"))
        assert result["id"] == "CVE-2024-3094"
        assert mock_get.call_args[0][0].endswith("/cve/CVE-2024-3094")


def test_fetch_circl_cve_browse_products_uses_vendor_in_path():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"product": ["windows"]})
        result = fetch_circl_cve_browse_products(
            CirclCveBrowseProductsParams(vendor="microsoft")
        )
        assert result["product"] == ["windows"]
        assert mock_get.call_args[0][0].endswith("/browse/microsoft")


def test_fetch_circl_cve_search_threads_vendor_and_product():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"results": [{"id": "CVE-2024-0001"}]})
        result = fetch_circl_cve_search(
            CirclCveSearchParams(vendor="oracle", product="mysql")
        )
        assert result["results"][0]["id"] == "CVE-2024-0001"
        assert mock_get.call_args[1]["params"] == {
            "vendor": "oracle",
            "product": "mysql",
        }


@pytest.mark.parametrize(
    ("factory", "kwargs"),
    [
        (CirclCveLastParams, {"limit": 0}),
        (CirclCveGetParams, {"cve_id": ""}),
        (CirclCveBrowseProductsParams, {"vendor": ""}),
        (CirclCveSearchParams, {"vendor": "", "product": "mysql"}),
        (CirclCveSearchParams, {"vendor": "oracle", "product": ""}),
    ],
)
def test_circl_params_validate_non_empty_values(factory, kwargs):
    with pytest.raises(Exception):
        factory(**kwargs)


@pytest.mark.anyio
async def test_circl_cve_last_success():
    """Smoke test: circl-cve-last returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_circl_cve_last({"limit": 1})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_circl_cve_last_http_error():
    """circl-cve-last propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_circl_cve_last({"limit": 1})


@pytest.mark.anyio
async def test_circl_cve_get_success():
    """Smoke test: circl-cve-get returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_circl_cve_get({"cve_id": "test"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_circl_cve_get_http_error():
    """circl-cve-get propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_circl_cve_get({"cve_id": "test"})


@pytest.mark.anyio
async def test_circl_cve_browse_vendors_success():
    """Smoke test: circl-cve-browse-vendors returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_circl_cve_browse_vendors({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_circl_cve_browse_vendors_http_error():
    """circl-cve-browse-vendors propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_circl_cve_browse_vendors({})


@pytest.mark.anyio
async def test_circl_cve_browse_products_success():
    """Smoke test: circl-cve-browse-products returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_circl_cve_browse_products({"vendor": "test"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_circl_cve_browse_products_http_error():
    """circl-cve-browse-products propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_circl_cve_browse_products({"vendor": "test"})


@pytest.mark.anyio
async def test_circl_cve_search_success():
    """Smoke test: circl-cve-search returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_circl_cve_search({"vendor": "test", "product": "test"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_circl_cve_search_http_error():
    """circl-cve-search propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_circl_cve_search({"vendor": "test", "product": "test"})
