"""Auto-generated tests for the global-doaj provider.

Generated by tools/generate_provider.py — feel free to extend with
tool-specific assertions once the provider stabilizes.
"""

from unittest.mock import Mock, patch

import httpx
import pytest

from meta_data_mcp.providers.global_doaj import (
    DoajSearchArticlesParams,
    DoajSearchJournalsParams,
    fetch_doaj_search_articles,
    fetch_doaj_search_journals,
    handle_doaj_search_articles,
    handle_doaj_search_journals,
)


@pytest.fixture
def anyio_backend():
    return "asyncio"


def _ok(payload):
    response = Mock()
    response.json.return_value = payload
    response.raise_for_status = Mock()
    response.status_code = 200
    response.headers = {}
    return response


def test_fetch_doaj_search_articles_maps_page_size_to_upstream_param():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"results": [{"id": "article-1"}]})
        result = fetch_doaj_search_articles(
            DoajSearchArticlesParams(q="climate", page=2, page_size=5),
        )
        assert result["results"][0]["id"] == "article-1"
        assert mock_get.call_args[0][0].endswith("/articles/")
        sent = mock_get.call_args[1]["params"]
        assert sent == {"q": "climate", "page": 2, "pageSize": 5}


def test_fetch_doaj_search_journals_maps_page_size_to_upstream_param():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"results": [{"id": "journal-1"}]})
        result = fetch_doaj_search_journals(
            DoajSearchJournalsParams(q="biology", page=3, page_size=10),
        )
        assert result["results"][0]["id"] == "journal-1"
        assert mock_get.call_args[0][0].endswith("/journals/")
        sent = mock_get.call_args[1]["params"]
        assert sent == {"q": "biology", "page": 3, "pageSize": 10}


@pytest.mark.parametrize(
    ("factory", "kwargs"),
    [
        (DoajSearchArticlesParams, {"q": ""}),
        (DoajSearchArticlesParams, {"q": "climate", "page": 0}),
        (DoajSearchArticlesParams, {"q": "climate", "page_size": 0}),
        (DoajSearchArticlesParams, {"q": "climate", "page_size": 101}),
        (DoajSearchJournalsParams, {"q": ""}),
        (DoajSearchJournalsParams, {"q": "biology", "page": 0}),
        (DoajSearchJournalsParams, {"q": "biology", "page_size": 0}),
        (DoajSearchJournalsParams, {"q": "biology", "page_size": 101}),
    ],
)
def test_doaj_params_validate_non_empty_queries_and_page_bounds(factory, kwargs):
    with pytest.raises(Exception):
        factory(**kwargs)


@pytest.mark.anyio
async def test_doaj_search_articles_success():
    """Smoke test: doaj-search-articles returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_doaj_search_articles({"q": "test"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_doaj_search_articles_http_error():
    """doaj-search-articles propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_doaj_search_articles({"q": "test"})


@pytest.mark.anyio
async def test_doaj_search_journals_success():
    """Smoke test: doaj-search-journals returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_doaj_search_journals({"q": "test"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_doaj_search_journals_http_error():
    """doaj-search-journals propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_doaj_search_journals({"q": "test"})
