"""Auto-generated tests for the eu-euvd provider.

Generated by tools/generate_provider.py — feel free to extend with
tool-specific assertions once the provider stabilizes.
"""

from unittest.mock import Mock, patch

import httpx
import pytest

from meta_data_mcp.providers.eu_euvd import (
    EuvdSearchVulnerabilitiesParams,
    fetch_euvd_search_vulnerabilities,
    handle_euvd_critical_vulnerabilities,
    handle_euvd_exploited_vulnerabilities,
    handle_euvd_latest_vulnerabilities,
    handle_euvd_search_vulnerabilities,
)


@pytest.fixture
def anyio_backend():
    return "asyncio"


def _ok(payload):
    response = Mock()
    response.json.return_value = payload
    response.raise_for_status = Mock()
    response.status_code = 200
    response.headers = {}
    return response


def test_fetch_euvd_search_vulnerabilities_maps_query_params():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"items": [{"id": "EUVD-1"}]})
        result = fetch_euvd_search_vulnerabilities(
            EuvdSearchVulnerabilitiesParams(
                text="openssl",
                vendor="OpenSSL",
                product="OpenSSL",
                assigner="MITRE",
                exploited=True,
                from_score=7.5,
                to_score=10.0,
                from_date="2025-01-01",
                to_date="2025-12-31",
                from_updated_date="2025-01-02",
                to_updated_date="2025-12-30",
                page=2,
                size=50,
            ),
        )
        assert result["items"][0]["id"] == "EUVD-1"
        sent = mock_get.call_args[1]["params"]
        assert sent == {
            "text": "openssl",
            "vendor": "OpenSSL",
            "product": "OpenSSL",
            "assigner": "MITRE",
            "exploited": True,
            "fromScore": 7.5,
            "toScore": 10.0,
            "fromDate": "2025-01-01",
            "toDate": "2025-12-31",
            "fromUpdatedDate": "2025-01-02",
            "toUpdatedDate": "2025-12-30",
            "page": 2,
            "size": 50,
        }


@pytest.mark.parametrize(
    "kwargs",
    [
        {"from_score": -1},
        {"to_score": 11},
        {"from_date": "2025/01/01"},
        {"to_updated_date": "not-a-date"},
        {"page": -1},
        {"size": 0},
        {"size": 101},
    ],
)
def test_euvd_search_params_validate_ranges_and_dates(kwargs):
    with pytest.raises(Exception):
        EuvdSearchVulnerabilitiesParams(**kwargs)


@pytest.mark.anyio
async def test_euvd_latest_vulnerabilities_success():
    """Smoke test: euvd-latest-vulnerabilities returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_euvd_latest_vulnerabilities({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_euvd_latest_vulnerabilities_http_error():
    """euvd-latest-vulnerabilities propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_euvd_latest_vulnerabilities({})


@pytest.mark.anyio
async def test_euvd_exploited_vulnerabilities_success():
    """Smoke test: euvd-exploited-vulnerabilities returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_euvd_exploited_vulnerabilities({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_euvd_exploited_vulnerabilities_http_error():
    """euvd-exploited-vulnerabilities propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_euvd_exploited_vulnerabilities({})


@pytest.mark.anyio
async def test_euvd_critical_vulnerabilities_success():
    """Smoke test: euvd-critical-vulnerabilities returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_euvd_critical_vulnerabilities({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_euvd_critical_vulnerabilities_http_error():
    """euvd-critical-vulnerabilities propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_euvd_critical_vulnerabilities({})


@pytest.mark.anyio
async def test_euvd_search_vulnerabilities_success():
    """Smoke test: euvd-search-vulnerabilities returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_euvd_search_vulnerabilities({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_euvd_search_vulnerabilities_http_error():
    """euvd-search-vulnerabilities propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_euvd_search_vulnerabilities({})
