"""Auto-generated tests for the global-ssllabs provider.

Generated by tools/generate_provider.py — feel free to extend with
tool-specific assertions once the provider stabilizes.
"""

from unittest.mock import Mock, patch

import httpx
import pytest

from meta_data_mcp.providers.global_ssllabs import (
    SsllabsAnalyzeParams,
    SsllabsEndpointDataParams,
    fetch_ssllabs_analyze,
    fetch_ssllabs_endpoint_data,
    handle_ssllabs_analyze,
    handle_ssllabs_endpoint_data,
    handle_ssllabs_info,
)


@pytest.fixture
def anyio_backend():
    return "asyncio"


def _ok(payload):
    response = Mock()
    response.json.return_value = payload
    response.raise_for_status = Mock()
    response.status_code = 200
    response.headers = {}
    return response


def test_fetch_ssllabs_analyze_maps_camel_case_query_params():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"status": "READY"})
        result = fetch_ssllabs_analyze(
            SsllabsAnalyzeParams(
                host="example.com",
                publish="off",
                start_new="on",
                from_cache="off",
                all="on",
                ignore_mismatch="off",
            ),
        )
        assert result["status"] == "READY"
        assert mock_get.call_args[1]["params"] == {
            "host": "example.com",
            "publish": "off",
            "startNew": "on",
            "fromCache": "off",
            "all": "on",
            "ignoreMismatch": "off",
        }


def test_fetch_ssllabs_endpoint_data_maps_from_cache_param():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"statusMessage": "Ready"})
        result = fetch_ssllabs_endpoint_data(
            SsllabsEndpointDataParams(
                host="example.com",
                ip="93.184.216.34",
                from_cache="on",
            ),
        )
        assert result["statusMessage"] == "Ready"
        assert mock_get.call_args[1]["params"] == {
            "host": "example.com",
            "ip": "93.184.216.34",
            "fromCache": "on",
        }


@pytest.mark.parametrize(
    "kwargs",
    [
        {"host": ""},
        {"host": "example.com", "publish": "yes"},
        {"host": "example.com", "start_new": "yes"},
        {"host": "example.com", "from_cache": "yes"},
        {"host": "example.com", "all": "yes"},
        {"host": "example.com", "ignore_mismatch": "yes"},
    ],
)
def test_ssllabs_analyze_params_validate_inputs(kwargs):
    with pytest.raises(Exception):
        SsllabsAnalyzeParams(**kwargs)


@pytest.mark.parametrize(
    "kwargs",
    [
        {"host": "", "ip": "1.1.1.1"},
        {"host": "example.com", "ip": "", "from_cache": "on"},
        {"host": "example.com", "ip": "1.1.1.1", "from_cache": "yes"},
    ],
)
def test_ssllabs_endpoint_data_params_validate_inputs(kwargs):
    with pytest.raises(Exception):
        SsllabsEndpointDataParams(**kwargs)


@pytest.mark.anyio
async def test_ssllabs_analyze_success():
    """Smoke test: ssllabs-analyze returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_ssllabs_analyze({"host": "test"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_ssllabs_analyze_http_error():
    """ssllabs-analyze propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_ssllabs_analyze({"host": "test"})


@pytest.mark.anyio
async def test_ssllabs_endpoint_data_success():
    """Smoke test: ssllabs-endpoint-data returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_ssllabs_endpoint_data({"host": "test", "ip": "test"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_ssllabs_endpoint_data_http_error():
    """ssllabs-endpoint-data propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_ssllabs_endpoint_data({"host": "test", "ip": "test"})


@pytest.mark.anyio
async def test_ssllabs_info_success():
    """Smoke test: ssllabs-info returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_ssllabs_info({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_ssllabs_info_http_error():
    """ssllabs-info propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_ssllabs_info({})
