"""Auto-generated tests for the ch-opendata-swiss provider.

Generated by tools/generate_provider.py — feel free to extend with
tool-specific assertions once the provider stabilizes.
"""

from unittest.mock import Mock, patch

import httpx
import pytest

from meta_data_mcp.providers.ch_opendata_swiss import (
    handle_ch_opendata_package_search,
    handle_ch_opendata_organization_list,
    handle_ch_opendata_tag_list,
)


@pytest.fixture
def anyio_backend():
    return "asyncio"


@pytest.mark.anyio
async def test_ch_opendata_package_search_success():
    """Smoke test: ch-opendata-package-search returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {"ok": True, "marker": "GENERATED_TEST_MARKER"}
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_ch_opendata_package_search({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_ch_opendata_package_search_http_error():
    """ch-opendata-package-search propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_ch_opendata_package_search({})


@pytest.mark.anyio
async def test_ch_opendata_organization_list_success():
    """Smoke test: ch-opendata-organization-list returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {"ok": True, "marker": "GENERATED_TEST_MARKER"}
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_ch_opendata_organization_list({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_ch_opendata_organization_list_http_error():
    """ch-opendata-organization-list propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_ch_opendata_organization_list({})


@pytest.mark.anyio
async def test_ch_opendata_tag_list_success():
    """Smoke test: ch-opendata-tag-list returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {"ok": True, "marker": "GENERATED_TEST_MARKER"}
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_ch_opendata_tag_list({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_ch_opendata_tag_list_http_error():
    """ch-opendata-tag-list propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_ch_opendata_tag_list({})
