"""Auto-generated tests for the global-rest-countries provider.

Generated by tools/generate_provider.py — feel free to extend with
tool-specific assertions once the provider stabilizes.
"""

from unittest.mock import Mock, patch

import httpx
import pytest

from meta_data_mcp.providers.global_rest_countries import (
    RestcountriesGetByCodeParams,
    RestcountriesListByRegionParams,
    RestcountriesSearchByNameParams,
    fetch_restcountries_get_by_code,
    fetch_restcountries_list_by_region,
    fetch_restcountries_search_by_name,
    handle_restcountries_search_by_name,
    handle_restcountries_get_by_code,
    handle_restcountries_list_by_region,
    handle_restcountries_list_all,
)


@pytest.fixture
def anyio_backend():
    return "asyncio"


def _ok(payload):
    response = Mock()
    response.json.return_value = payload
    response.raise_for_status = Mock()
    response.status_code = 200
    response.headers = {}
    return response


def test_fetch_restcountries_search_by_name_uses_name_in_path():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok([{"name": {"common": "Germany"}}])
        result = fetch_restcountries_search_by_name(
            RestcountriesSearchByNameParams(name="Germany")
        )
        assert result[0]["name"]["common"] == "Germany"
        assert mock_get.call_args[0][0].endswith("/name/Germany")


def test_fetch_restcountries_get_by_code_uses_code_in_path():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok([{"cca2": "DE"}])
        result = fetch_restcountries_get_by_code(RestcountriesGetByCodeParams(code="DE"))
        assert result[0]["cca2"] == "DE"
        assert mock_get.call_args[0][0].endswith("/alpha/DE")


def test_fetch_restcountries_list_by_region_uses_region_in_path():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok([{"region": "Europe"}])
        result = fetch_restcountries_list_by_region(
            RestcountriesListByRegionParams(region="Europe")
        )
        assert result[0]["region"] == "Europe"
        assert mock_get.call_args[0][0].endswith("/region/Europe")


@pytest.mark.parametrize(
    ("factory", "kwargs"),
    [
        (RestcountriesSearchByNameParams, {"name": ""}),
        (RestcountriesGetByCodeParams, {"code": ""}),
        (RestcountriesListByRegionParams, {"region": ""}),
    ],
)
def test_string_params_reject_empty_values(factory, kwargs):
    with pytest.raises(Exception):
        factory(**kwargs)


@pytest.mark.anyio
async def test_restcountries_search_by_name_success():
    """Smoke test: restcountries-search-by-name returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_restcountries_search_by_name({"name": "test"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_restcountries_search_by_name_http_error():
    """restcountries-search-by-name propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_restcountries_search_by_name({"name": "test"})


@pytest.mark.anyio
async def test_restcountries_get_by_code_success():
    """Smoke test: restcountries-get-by-code returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_restcountries_get_by_code({"code": "test"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_restcountries_get_by_code_http_error():
    """restcountries-get-by-code propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_restcountries_get_by_code({"code": "test"})


@pytest.mark.anyio
async def test_restcountries_list_by_region_success():
    """Smoke test: restcountries-list-by-region returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_restcountries_list_by_region({"region": "test"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_restcountries_list_by_region_http_error():
    """restcountries-list-by-region propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_restcountries_list_by_region({"region": "test"})


@pytest.mark.anyio
async def test_restcountries_list_all_success():
    """Smoke test: restcountries-list-all returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_restcountries_list_all({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_restcountries_list_all_http_error():
    """restcountries-list-all propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_restcountries_list_all({})
