"""Auto-generated tests for the de-govdata provider.

Generated by tools/generate_provider.py — feel free to extend with
tool-specific assertions once the provider stabilizes.
"""

from unittest.mock import Mock, patch

import httpx
import pytest

from meta_data_mcp.providers.de_govdata import (
    handle_de_govdata_package_search,
    handle_de_govdata_organization_list,
    handle_de_govdata_group_list,
)


@pytest.fixture
def anyio_backend():
    return "asyncio"


@pytest.mark.anyio
async def test_de_govdata_package_search_success():
    """Smoke test: de-govdata-package-search returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {
            "ok": True,
            "marker": "GENERATED_TEST_MARKER",
        }
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_de_govdata_package_search({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_de_govdata_package_search_http_error():
    """de-govdata-package-search propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_de_govdata_package_search({})


@pytest.mark.anyio
async def test_de_govdata_organization_list_success():
    """Smoke test: de-govdata-organization-list returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {
            "ok": True,
            "marker": "GENERATED_TEST_MARKER",
        }
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_de_govdata_organization_list({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_de_govdata_organization_list_http_error():
    """de-govdata-organization-list propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_de_govdata_organization_list({})


@pytest.mark.anyio
async def test_de_govdata_group_list_success():
    """Smoke test: de-govdata-group-list returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {
            "ok": True,
            "marker": "GENERATED_TEST_MARKER",
        }
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_de_govdata_group_list({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_de_govdata_group_list_http_error():
    """de-govdata-group-list propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_de_govdata_group_list({})
