"""Auto-generated tests for the global-crtsh provider.

Generated by tools/generate_provider.py — feel free to extend with
tool-specific assertions once the provider stabilizes.
"""

from unittest.mock import Mock, patch

import httpx
import pytest

from meta_data_mcp.providers.global_crtsh import (
    CrtshSearchCertificatesParams,
    fetch_crtsh_search_certificates,
    handle_crtsh_search_certificates,
)


@pytest.fixture
def anyio_backend():
    return "asyncio"


def _ok(payload):
    response = Mock()
    response.json.return_value = payload
    response.raise_for_status = Mock()
    response.status_code = 200
    response.headers = {}
    return response


def test_fetch_crtsh_search_certificates_forces_json_output():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok([{"common_name": "example.com"}])
        result = fetch_crtsh_search_certificates(
            CrtshSearchCertificatesParams(q="example.com", exclude="expired"),
        )
        assert result[0]["common_name"] == "example.com"
        assert mock_get.call_args[1]["params"] == {
            "q": "example.com",
            "output": "json",
            "exclude": "expired",
        }


@pytest.mark.parametrize(
    "kwargs",
    [
        {"q": ""},
        {"q": "example.com", "exclude": ""},
    ],
)
def test_crtsh_params_reject_empty_values(kwargs):
    with pytest.raises(Exception):
        CrtshSearchCertificatesParams(**kwargs)


@pytest.mark.anyio
async def test_crtsh_search_certificates_success():
    """Smoke test: crtsh-search-certificates returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok({"ok": True, "marker": "GENERATED_TEST_MARKER"})
        result = await handle_crtsh_search_certificates({"q": "test"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_crtsh_search_certificates_http_error():
    """crtsh-search-certificates propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_crtsh_search_certificates({"q": "test"})
