"""Auto-generated tests for the global-solarsystem provider.

Generated by tools/generate_provider.py — feel free to extend with
tool-specific assertions once the provider stabilizes.
"""

from unittest.mock import Mock, patch

import httpx
import pytest

from meta_data_mcp.providers.global_solarsystem import (
    handle_solarsystem_list_bodies,
    handle_solarsystem_get_body,
    handle_solarsystem_known_count,
)


@pytest.fixture
def anyio_backend():
    return "asyncio"


@pytest.mark.anyio
async def test_solarsystem_list_bodies_success():
    """Smoke test: solarsystem-list-bodies returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {"ok": True, "marker": "GENERATED_TEST_MARKER"}
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_solarsystem_list_bodies({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_solarsystem_list_bodies_http_error():
    """solarsystem-list-bodies propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_solarsystem_list_bodies({})


@pytest.mark.anyio
async def test_solarsystem_get_body_success():
    """Smoke test: solarsystem-get-body returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {"ok": True, "marker": "GENERATED_TEST_MARKER"}
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_solarsystem_get_body({'body_id': 'test'})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_solarsystem_get_body_http_error():
    """solarsystem-get-body propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_solarsystem_get_body({'body_id': 'test'})


@pytest.mark.anyio
async def test_solarsystem_known_count_success():
    """Smoke test: solarsystem-known-count returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value.json.return_value = {"ok": True, "marker": "GENERATED_TEST_MARKER"}
        mock_get.return_value.raise_for_status = Mock()
        mock_get.return_value.status_code = 200
        result = await handle_solarsystem_known_count({})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_solarsystem_known_count_http_error():
    """solarsystem-known-count propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_solarsystem_known_count({})
