"""Auto-generated tests for the global-pwned-passwords provider.

Generated by tools/generate_provider.py — feel free to extend with
tool-specific assertions once the provider stabilizes.
"""

from unittest.mock import Mock, patch

import httpx
import pytest

from meta_data_mcp.providers.global_pwned_passwords import (
    PwnedPasswordsRangeParams,
    fetch_pwned_passwords_range,
    handle_pwned_passwords_range,
)
from meta_data_mcp.utils import MAX_RESPONSE_CHARS


@pytest.fixture
def anyio_backend():
    return "asyncio"


def _ok(text):
    response = Mock()
    response.text = text
    response.raise_for_status = Mock()
    response.status_code = 200
    response.headers = {}
    return response


def test_fetch_pwned_passwords_range_uppercases_prefix():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok("ABCDEF:42")
        result = fetch_pwned_passwords_range(
            PwnedPasswordsRangeParams(sha1_prefix="abcde"),
        )
        assert result == "ABCDEF:42"
        assert mock_get.call_args[0][0].endswith("/range/ABCDE")
        assert mock_get.call_args.kwargs["headers"]["Accept"] == "text/plain"


@pytest.mark.parametrize(
    "prefix",
    ["", "abcd", "abcdef", "zzzzz", "12 45"],
)
def test_pwned_passwords_prefix_validation(prefix):
    with pytest.raises(Exception):
        PwnedPasswordsRangeParams(sha1_prefix=prefix)


@pytest.mark.anyio
async def test_pwned_passwords_range_success():
    """Smoke test: pwned-passwords-range returns success payload."""
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok("GENERATED_TEST_MARKER")
        result = await handle_pwned_passwords_range({"sha1_prefix": "ABCDE"})
        assert len(result) == 1
        assert "GENERATED_TEST_MARKER" in result[0].text


@pytest.mark.anyio
async def test_pwned_passwords_range_http_error():
    """pwned-passwords-range propagates httpx errors."""
    with patch("httpx.get") as mock_get:
        mock_get.side_effect = httpx.HTTPError("Network down")
        with pytest.raises(httpx.HTTPError):
            await handle_pwned_passwords_range({"sha1_prefix": "ABCDE"})


@pytest.mark.anyio
async def test_pwned_passwords_range_truncates_to_max_response_chars():
    with patch("httpx.get") as mock_get:
        mock_get.return_value = _ok("A" * (MAX_RESPONSE_CHARS + 10))
        result = await handle_pwned_passwords_range({"sha1_prefix": "ABCDE"})
        assert len(result[0].text) == MAX_RESPONSE_CHARS
